"""Seed initial message

Revision ID: 6143f6218c25
Revises: f69d316befb9
Create Date: 2025-12-25 17:26:58.547786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6143f6218c25'
down_revision: Union[str, Sequence[str], None] = 'f69d316befb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "INSERT INTO message (role, type, content, created_at, updated_at, is_deleted) "
        "VALUES ('system', 'text', 'hi', NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC', FALSE)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DELETE FROM message WHERE role='system' AND type='text' AND content='hi'"
    )
