"""Create Message table

Revision ID: f69d316befb9
Revises: 
Create Date: 2025-12-25 16:56:12.521272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Added to resolve NameError


# revision identifiers, used by Alembic.
revision: str = 'f69d316befb9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('feedback', sa.JSON(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('tool_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tool_code_result', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_agent_id'), 'message', ['agent_id'], unique=False)
    op.create_index(op.f('ix_message_parent_id'), 'message', ['parent_id'], unique=False)
    op.create_index(op.f('ix_message_run_id'), 'message', ['run_id'], unique=False)
    op.create_index(op.f('ix_message_session_id'), 'message', ['session_id'], unique=False)
    op.create_index(op.f('ix_message_user_id'), 'message', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_user_id'), table_name='message')
    op.drop_index(op.f('ix_message_session_id'), table_name='message')
    op.drop_index(op.f('ix_message_run_id'), table_name='message')
    op.drop_index(op.f('ix_message_parent_id'), table_name='message')
    op.drop_index(op.f('ix_message_agent_id'), table_name='message')
    op.drop_table('message')
    # ### end Alembic commands ###
